# Generated by Django 3.2 on 2021-09-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_integrationuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
    ]
